checkm2_db_dir: /mnt/hpccs01/work/microbiome/db/CheckM2_database/
gunc_db_dir: /mnt/hpccs01/work/microbiome/users/heyu/db/gunc_db/
ncbi16s_dir: /mnt/hpccs01/work/microbiome/users/heyu/db/ncbi_16S/
gtdbtk_db_dir: /mnt/hpccs01/work/microbiome/db/gtdb/gtdb_release232/auxillary_files/gtdbtk_package/full_package/release232

max_threads:
  gtdbtk: 32
  gtdbtk_pplacer: 3
  checkm2: 8
  gunc: 8
  blastn: 4

directories:
  seqkit: 01_stats/seqkit
  orfs: 02_genes/orfs
  rrna: 02_genes/rrna
  trna: 02_genes/trna
  checkm: 03_quality/checkm
  gunc: 03_quality/gunc
  park: 03_quality/park
  mimag: 03_quality/mimag
  gtdbtk: 04_taxonomy/gtdbtk
  r16s: 04_taxonomy/16S
  logs: logs
  benchmarks: benchmarks

output_files:
  summary: MAGport_summary.tsv
  report: MAGport_report.html
report_title: MAGport Report


